const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const morgan = require('morgan')
const app = express()
var mongoose = require('mongoose')

var posts = require('./routes/posts')
var experiments = require('./routes/experiments')
var projects = require('./routes/projects')
var users = require('./routes/users')
app.use(morgan('combined'))
app.use(bodyParser.json())
app.use(cors())

app.use('/posts',posts)
app.use('/experiments',experiments)
app.use('/projects',projects)
app.use('/users',users)
app.listen(process.env.PORT || 8081)
console.log()
